"""Constants for the Camect integration."""

DOMAIN = "camect"
ATTR_CAMECT_MAKE = "Camect"
ATTR_CAMECT_MODEL = "Hub"
ATTR_CAMECT_HUBMODESWITCH = "Hub mode switch"
ATTR_HUB_MODE = "Hub Mode"
ATTR_MODE_DEFAULT = "DEFAULT"
ATTR_MODE_HOME = "HOME"
ATTR_MODE_REASON = "HomeAssistant"

ATTR_MOTION = "motion"
ATTR_MOTION_LABEL = "Motion"

ATTR_RAW_DATA = "raw_data"
ATTR_ALERT = "alert"
ATTR_ALERT_DISABLED = "is_alert_disabled"
ATTR_ALERT_ENABLED = "Alerts Enabled"
ATTR_CAM_OFFLINE = "camera_offline"
ATTR_CAM_ONLINE = "camera_online"
ATTR_UNKNOWN_OBJ = "unknown object"

SERVICE_CHANGE_OP_MODE = "change_op_mode"
SERVICE_DISABLE_CAMERA_ALERT = "disable_camera_alert"
SERVICE_ENABLE_CAMERA_ALERT = "enable_camera_alert"
CAMERA_IDS = "camera"

CONF_SUBTYPE = "subtype"
ATTR_CAMECT_EVENT = "camect_event"

LOGBOOK_ENTRY_CONTEXT_ID = "context_id"
LOGBOOK_ENTRY_DOMAIN = "domain"
LOGBOOK_ENTRY_ENTITY_ID = "entity_id"
LOGBOOK_ENTRY_ICON = "icon"
LOGBOOK_ENTRY_SOURCE = "source"
LOGBOOK_ENTRY_MESSAGE = "message"
LOGBOOK_ENTRY_NAME = "name"
LOGBOOK_ENTRY_STATE = "state"
LOGBOOK_ENTRY_WHEN = "when"
